title: Hyeonmo Koo
theme: jekyll-theme-cayman

collections:
  pages:

nav:
  - name: Home
    link: /
  - name: About
    link: /about
  - name: Research
    link: /research
  - name: CV
    link: /cv
