theme: minima

title: Hyeonmo Koo
author: Hyeonmo Koo
description: "Hyeonmo's personal academic website."

# --- 네비게이션 메뉴 설정 ---
header_pages:
  - about.md
  - research.md
  - publication.md
  - cv.md
