title: "Hyeonmo Koo"
description: "PhD in Physics – Ultralight Dark Matter, Dynamical Friction, Galaxy Dynamics"
theme: minima

# 여기가 메뉴에 들어갈 페이지 목록입니다.
header_pages:
  - research.md
  - publications.md
  - cv.md
